import type { Metadata } from 'next';
import { Sora as FontMono, Geist as FontSans } from 'next/font/google';
import './globals.css';
import { ClientProvider } from '@/app/client-provider';
import { ThemeProvider } from '@/lib/theme-provider';

const fontSans = FontSans({
  variable: '--font-sans',
  subsets: ['latin'],
});

const fontMono = FontMono({
  variable: '--font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
          enableSystem={false}
        >
          <ClientProvider>{children}</ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
